package com.company.context;

public class ContextException extends Exception {
    // Generated by IDE
    private static final long serialVersionUID = -1377660338804708269L;

    ContextException(String msg) {
        super(msg);
    }
}