package com.company.context;

public class IllegalConfigException extends Exception {
    // Generated by IDE
    private static final long serialVersionUID = 7191290595331037838L;

    IllegalConfigException(String msg) {
        super(msg);
    }
}