package com.company.context;

public class IllegalBeanException extends Exception {
    // Generated by IDE
    private static final long serialVersionUID = -5668599970942419193L;

    IllegalBeanException(String msg) {
        super(msg);
    }
}